# Generated by Django 5.1.4 on 2025-01-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('instapay', 'Instapay'), ('cash', 'Cash'), ('wallet', 'E-Wallet')], max_length=50),
        ),
    ]
