# Generated by Django 5.1.4 on 2025-01-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('social_media', 'Social Media Management'), ('coding', 'Coding Portfolio'), ('app_development', 'App Development'), ('ecommerce', 'E-commerce Site'), ('custom_system', 'Custom System')], max_length=50)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_semi_annual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_annual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
